AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: cfnosabucket

Outputs:
  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref S3Bucket
